spring:
  application:
    name: admin-service
  config:
    import: "optional:configserver:"  
    
  datasource:
    url: jdbc:mysql://localhost:3306/fitness-admin?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
 
server:
  port: 8000
    
