server:
  port: 8100
  
spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:"   
  datasource:
    url: jdbc:mysql://localhost:3306/fitness-order?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  